[theme]
base = "dark"
backgroundColor = "#0d0d0d"
secondaryBackgroundColor = "#161616"
textColor = "#e8e8e8"
primaryColor = "#c8873f"
font = "sans serif"

[server]
maxUploadSize = 10

[browser]
gatherUsageStats = false
